name: "Build darwin cache"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v6
        with:
          name: peel
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'        
      - run: cachix use nix-community
      - run: cachix use peel
      - run: nix-build darwin.nix
